server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${NEON_HOST:postgres}:5432/eventflow?sslmode=require&ssl=true
    username: ${NEON_USER:neondb_owner}
    password: ${NEON_PASSWORD:eventflow_secret}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_USERNAME:}' password='${KAFKA_PASSWORD:}';"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:}
